spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://auth-service-db:5432/db
    username: user_admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  sql:
    init:
      mode: always

server:
  port: 4005
