spring:
  application:
    name: Patient-Service

  datasource:
    url: jdbc:postgresql://localhost:5001/postgres
    username: admin_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 4000

# Optional: Add logging to debug database connection
logging:
  level:
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG