-- Create table if not exists
CREATE TABLE IF NOT EXISTS patient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    registered_date DATE NOT NULL
);

-- Insert 10 sample patient records only if they don't exist
INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Alice Johnson', 'alice.johnson@example.com', '123 Main St, New York', '1990-03-15', '2024-09-10')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Bob Smith', 'bob.smith@example.com', '456 Oak Ave, Los Angeles', '1985-07-22', '2024-09-11')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Charlie Brown', 'charlie.brown@example.com', '789 Pine Rd, Chicago', '1992-11-05', '2024-09-12')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Diana Prince', 'diana.prince@example.com', '321 Elm St, Houston', '1988-01-25', '2024-09-13')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Ethan Hunt', 'ethan.hunt@example.com', '654 Maple Blvd, Phoenix', '1983-09-09', '2024-09-14')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Fiona Adams', 'fiona.adams@example.com', '987 Cedar Dr, Seattle', '1995-05-17', '2024-09-15')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('George Miller', 'george.miller@example.com', '159 Birch Ln, Denver', '1979-02-02', '2024-09-16')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Hannah Lee', 'hannah.lee@example.com', '753 Spruce Ct, Miami', '1991-06-28', '2024-09-17')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Ian Clarke', 'ian.clarke@example.com', '852 Walnut Way, Boston', '1993-08-10', '2024-09-18')
ON CONFLICT (email) DO NOTHING;

INSERT INTO patient (name, email, address, date_of_birth, registered_date)
VALUES
('Julia Roberts', 'julia.roberts@example.com', '951 Poplar Ave, Dallas', '1989-12-19', '2024-09-19')
ON CONFLICT (email) DO NOTHING;